spring.application.name=driveeasy

spring.datasource.url=jdbc:mysql://localhost:3306/driveeasy_db
spring.datasource.username=root
spring.datasource.password=ramidwar

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081